VERSION = '20190707_0135a'

GUI_BACKGROUND = 'lightgray'
GUI_PROGRESS_BAR_PROGRESS_MADE = 'lightblue'
GUI_PROGRESS_BAR_PROGRESS_LEFT = 'darkgray'
GUI_REFRESH_RATE_MS = 100

HIVEMQ_BROKER = 'broker.hivemq.com'
HYPERION_BROKER = '10.108.132.101'
DEFAULT_BROKER = HIVEMQ_BROKER

